### ISSUE TITLE
Change Game Settings

### ISSUE THREAD

**Issue by Squigspear** [diambra/arena#116]
Hi, would it be possible to change game settings for multiplayer environments?
Settings such as match duration, or even multi-round matches? 

Currently, the game ends when one side HP gets to zero in a single round, without continuing to the next round.

Would there be a way to either a) extend the match duration for a longer period instead of a default or b) increase number of rounds played in a single session for the agent, just like the single player environment.

**Comment by alexpalms** [comment]
Hi @Squigspear, thanks for reaching out. 

I would like to make sure I properly understand your request/note.

> Currently, the game ends when one side HP gets to zero in a single round, without continuing to the next round.

Actually the general rule is (or should be) that an _episode_ in the 2P mode ends when one of the two players wins the number of rounds prescribed by the specific game. In some games this number is 1, while in some others is 2. I am saying this because if you are noticing something different it might be a bug.

Can you please give some additional context, in particular:
- OS
- Game you are using

And maybe upload a screenshot?

**Comment by Squigspear** [comment]
Hi @alexpalms, Thank you for the prompt reply! Really appreciate it. 

The issue of a single round win ending the match has been solved. It is a code issue on my end where the env closes on a single round win. I have since corrected it.

This issue can be closed.

OS - Ubuntu 22.04.4 LTS
Game -  Street Fighter III 3rd Strike

**Comment by alexpalms** [comment]
Great @Squigspear, thanks for getting back to us and happy you manged to solve it. Do not hesitate to let us know if you need anything else and for support you can reach out on our Discord Server! ;)
