### ISSUE TITLE
Sound Issues

### ISSUE THREAD

**Issue by Squigspear** [diambra/arena#117]
Hi, I have a sound issue. 

There is no sound when the environment is played. Appreciate is anyone can help out with this!

command ran: diambra -r ~/.diambra/roms run -l python3 script.py

Here is the error message: 
(0676) ALSA lib conf.c:4553:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

OS: Ubuntu 22.04.4 LTS
Game: SF3 Third Strike
Version: diambra 0.0.18

**Comment by alexpalms** [comment]
@Squigspear In order to have the sound (together with the "normal" or "expected" execution/graphics) you have to follow the steps highlighted [here](https://docs.diambra.ai/gettingstarted/#environment-native-rendering) and [here](https://docs.diambra.ai/gettingstarted/#diambra-cli-advanced-options).

Basically changing your command to:
`diambra -r ~/.diambra/roms run -l -g --engine.sound python3 script.py`

Try that and let us know.

PS: for this type of support questions you can also directly ask on our [Discord Server](https://diambra.ai/discord), which is usually faster

**Comment by Squigspear** [comment]
Thanks @alexpalms for the suggestion. 

Tried it but it gives an error:
Couldn't run: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/.X11-unix  

I will bring it to the discord server for this type of support questions! Closing this issue.

**Comment by alexpalms** [comment]
@Squigspear thanks for getting back to us. Well if something is confirmed that is not working, is good to open an issue, the support channel is the first place to ask how to do something. In this case it seems that there is something that is not working properly in your configuration, so feel free to open an issue for that.
